#!/bin/zsh
# ====================[ zlogin                             ]====================
#                     [ Time-stamp: "2008-10-27 03:30:32 leycec" ]
#
# --------------------( SYNOPSIS                           )--------------------
# Run after "zshenv", "zprofile", and "zshrc", for login shells. This is the
# last script ZSH calls when starting up.

# ....................{ INITIALIZATION                     }....................
# Import core declarations.
[[ -n "${ZSHENV_CORE_SOURCED}" ]] ||
    source "$(readlink --canonicalize-existing $(dirname "${0}"))/zshenv.core"
echo "zeshy: loading \"${ZSHRC_HOME}/zlogin\"..."

# ....................{ DECONSTRUCTION                     }....................
# Destroy all existing temporary, connection-specific files.
#SSH_CONTROLMASTER_SOCKETS=$(~/tmp/ssh_controlmaster*);

#if [ $? == 0 ]; then
# for SSH_CONTROLMASTER_SOCKET in ~/tmp/ssh_controlmaster*; do
#   mv --force $SSH_CONTROLMASTER_SOCKET /tmp/
# done
#fi

# ....................{ SCREEN BLANKING                    }....................
#FIXME: Selectively enable only for the "aty128fb" device.
# Disable screen blanking (via APM), VESA powersave, and VESA powerdown features
# on this virtual (vcs) console. These features often corrupt the display on
# framebuffer devices unable to adeptly change resolution-- particularly, the
# "aty128fb" framebuffer device on iBook G3 500Mhz LCDs.
#
# If the user is already running X.org, this does nothing.
#[ -z "$DISPLAY" ] && setterm -powersave off -blank 0 -powerdown 0

# --------------------( COPYRIGHT AND LICENSE              )--------------------
# The information below applies to everything in this distribution,
# except where noted.
#              
# Copyleft 2010 by Cecil Curry.
#   
#   http://www.raiazome.com
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
